# Generated by Django 4.0.5 on 2024-06-08 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSenderTable',
            fields=[
                ('token_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('token_busy', models.IntegerField(default=1)),
                ('token_sender_id', models.CharField(blank=True, max_length=30)),
                ('token_receiver_id', models.CharField(blank=True, max_length=30)),
                ('token_color', models.CharField(max_length=2)),
                ('token_time', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('token_turn', models.CharField(max_length=2)),
                ('token_last_joiner', models.CharField(blank=True, max_length=50)),
                ('chessboard', models.TextField()),
                ('castle', models.TextField()),
                ('dead_list', models.TextField(default='[]')),
                ('game_over', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WithComputerToken',
            fields=[
                ('token_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('token_busy', models.IntegerField(default=0)),
                ('token_color', models.CharField(max_length=2)),
                ('token_turn', models.CharField(max_length=2)),
                ('token_level', models.IntegerField(default=2)),
                ('chessboard', models.TextField()),
                ('castle', models.TextField()),
                ('dead_list', models.TextField(default='[]')),
                ('game_over', models.BooleanField(default=False)),
            ],
        ),
    ]
